name: UniDone CI/CD Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Auto-detect and Install
        run: |
          # Шукаємо папку, де лежить package.json (ігноруючи node_modules)
          TARGET_DIR=$(find . -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \; | head -n 1)
          echo "Found project in: $TARGET_DIR"
          cd "$TARGET_DIR"

          npm install
          # Використовуємо || true, щоб пайплайн не падав, якщо лінтер знайде дрібниці
          npm run lint || true 
          npm run build
